import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Nav from "@/components/Global/Nav";
import Footer from "@/components/Global/Footer";
import { BsWhatsapp } from "react-icons/bs";
import Link from "next/link";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Asian Wealth Jewellers",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Nav />
        <div className="">{children}</div>
        <Link href={`https://wa.me/+2348184564709`} className="p-[6px] duration-300 active:scale-95 pr-7 cursor-pointer rounded-full flex gap-4 items-center fixed bottom-8 text-white right-8 bg-gray-950 z-30">
          <div className="h-10 w-10 text-xl rounded-full bg-green-500 center">
            <BsWhatsapp />
          </div>
          <p className="text-10 font-semibold tracking-widest">SOURCE ME A WATCH</p>
        </Link>
        <Footer />
      </body>
    </html>
  );
}
